apiVersion: hive.openshift.io/v1
kind: ClusterClaim
metadata:
  name: '{{ .Values.clusterClaimName }}'
  annotations:
    argocd.argoproj.io/sync-wave: "350"
    helm.sh/hook-weight: "350"
  labels:
    name: {{ .Values.clusterClaimName }} 
  namespace: 'rhacm-clusterclaims'
spec:
  clusterPoolName: {{ .Values.clusterPoolName }}
