apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: '{{ .Values.cluster }}'
  annotations:
    argocd.argoproj.io/sync-wave: "360"
    helm.sh/hook-weight: "360"
  namespace: '{{ .Values.cluster }}'
  labels:
    cloud: 'IBM'
    region: '{{ .Values.provider.region }}'
    vendor: OpenShift
spec:
  baseDomain: {{ .Values.provider.baseDomain }}
  clusterName: '{{ .Values.cluster }}'
  powerState: {{ .Values.powerState }}
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  platform:
    ibmcloud:
      credentialsSecretRef:
        name: {{ .Values.cluster }}-ibmcloud-creds
      region: {{ .Values.provider.region }}
  provisioning:
    manifestsConfigMapRef:
      name: {{ .Values.cluster }}-manifests
    installConfigSecretRef:
      name: {{ .Values.cluster }}-install-config
    sshPrivateKeySecretRef:
      name: {{ .Values.cluster }}-ssh-private-key
    imageSetRef:
      name: {{ .Values.imageName }} 
  pullSecretRef:
    name: {{ .Values.cluster }}-pull-secret
