apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.cluster }}-ibmcloud-creds
  annotations:
    argocd.argoproj.io/sync-wave: "355"
    helm.sh/hook-weight: "355"
  namespace: {{ .Values.cluster }}
spec:
  encryptedData:
    ibmcloud_api_key: {{ .Values.provider.ibmcloud_api_key }}
  template:
    data: null
    metadata:
      name: {{ .Values.cluster }}-ibmcloud-creds
      namespace: {{ .Values.cluster }} 
    type: Opaque
